version: "3.7"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./docker/php
    volumes:
      - ./:/var/www

  redis:
    image: redis
